### PR TITLE
Workaround loading system resources on Samaung MTK devices

### PR DESCRIPTION
**Pull request by aviraxp**

### CODE REVIEW

**Comment by aviraxp** [comment]
Another workaround is setprop ro.vendor.model_mtk to 0, but that's not a good idea here as libsu is a common lib widely used in many projects.

**Comment by Mygod** [comment]
Assuming this fixes #185? Reopening that one.

**Comment by Mygod** [comment]
For what it's worth, from my sample size of 3, all of them are running Samsung Galaxy M53 5G (SM-M536B) Android 14. Possibly same build too.

**Comment by aviraxp** [comment]
@topjohnwu Do we still want this fixed in libsu, considered there are other root soultions?

**Pull request closed without merging**
